// <auto-generated />
namespace WebMarket.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ProductAddedName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductAddedName));
        
        string IMigrationMetadata.Id
        {
            get { return "201308241509132_ProductAddedName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
